export type PaletteSwatch = {
  name: string;
  className: string;
  label: string;
  token: string;
  invert?: boolean;
};

export const paletteSwatches: readonly PaletteSwatch[] = [
  {
    name: 'Background',
    className: 'bg-background',
    label: 'var(--background)',
    token: '--background',
  },
  {
    name: 'Foreground',
    className: 'bg-foreground',
    label: 'var(--foreground)',
    token: '--foreground',
    invert: true,
  },
  { name: 'Border', className: 'bg-border', label: 'var(--border)', token: '--border' },
  {
    name: 'Input',
    className: 'bg-input',
    label: 'var(--input)',
    token: '--input',
  },
  {
    name: 'Ring',
    className: 'bg-ring',
    label: 'var(--ring)',
    token: '--ring',
    invert: true,
  },
  {
    name: 'Wheel text',
    className: 'bg-wheel-foreground',
    label: 'var(--wheel-foreground)',
    token: '--wheel-foreground',
  },
  { name: 'Card', className: 'bg-card', label: 'var(--card)', token: '--card' },
  {
    name: 'Card border',
    className: 'bg-card-border',
    label: 'var(--card-border)',
    token: '--card-border',
  },
  {
    name: 'Popover border',
    className: 'bg-popover-border',
    label: 'var(--popover-border)',
    token: '--popover-border',
  },
  {
    name: 'Primary border',
    className: 'bg-primary-border',
    label: 'var(--primary-border)',
    token: '--primary-border',
    invert: true,
  },
  {
    name: 'Secondary border',
    className: 'bg-secondary-border',
    label: 'var(--secondary-border)',
    token: '--secondary-border',
  },
  {
    name: 'Accent border',
    className: 'bg-accent-border',
    label: 'var(--accent-border)',
    token: '--accent-border',
  },
  {
    name: 'Success border',
    className: 'bg-success-border',
    label: 'var(--success-border)',
    token: '--success-border',
    invert: true,
  },
  {
    name: 'Warning border',
    className: 'bg-warning-border',
    label: 'var(--warning-border)',
    token: '--warning-border',
  },
  {
    name: 'Destructive border',
    className: 'bg-destructive-border',
    label: 'var(--destructive-border)',
    token: '--destructive-border',
    invert: true,
  },
  {
    name: 'Primary',
    className: 'bg-primary',
    label: 'var(--primary)',
    token: '--primary',
    invert: true,
  },
  {
    name: 'Primary hover',
    className: 'bg-primary-hover',
    label: 'var(--primary-hover)',
    token: '--primary-hover',
    invert: true,
  },
  { name: 'Secondary', className: 'bg-secondary', label: 'var(--secondary)', token: '--secondary' },
  { name: 'Accent', className: 'bg-accent', label: 'var(--accent)', token: '--accent' },
  {
    name: 'Success',
    className: 'bg-success',
    label: 'var(--success)',
    token: '--success',
    invert: true,
  },
  { name: 'Warning', className: 'bg-warning', label: 'var(--warning)', token: '--warning' },
  { name: 'Muted', className: 'bg-muted', label: 'var(--muted)', token: '--muted' },
  {
    name: 'Destructive',
    className: 'bg-destructive',
    label: 'var(--destructive)',
    token: '--destructive',
    invert: true,
  },
  { name: 'Popover', className: 'bg-popover', label: 'var(--popover)', token: '--popover' },
  { name: 'Sidebar', className: 'bg-sidebar', label: 'var(--sidebar)', token: '--sidebar' },
  {
    name: 'Sidebar border',
    className: 'bg-sidebar-border',
    label: 'var(--sidebar-border)',
    token: '--sidebar-border',
  },
  {
    name: 'Sidebar foreground',
    className: 'bg-sidebar-foreground',
    label: 'var(--sidebar-foreground)',
    token: '--sidebar-foreground',
    invert: true,
  },
  {
    name: 'Sidebar primary',
    className: 'bg-sidebar-primary',
    label: 'var(--sidebar-primary)',
    token: '--sidebar-primary',
    invert: true,
  },
  {
    name: 'Sidebar primary hover',
    className: 'bg-sidebar-primary-hover',
    label: 'var(--sidebar-primary-hover)',
    token: '--sidebar-primary-hover',
    invert: true,
  },
  {
    name: 'Sidebar primary active',
    className: 'bg-sidebar-primary-active',
    label: 'var(--sidebar-primary-active)',
    token: '--sidebar-primary-active',
    invert: true,
  },
  {
    name: 'Sidebar primary foreground',
    className: 'bg-sidebar-primary-foreground',
    label: 'var(--sidebar-primary-foreground)',
    token: '--sidebar-primary-foreground',
  },
  {
    name: 'Sidebar accent',
    className: 'bg-sidebar-accent',
    label: 'var(--sidebar-accent)',
    token: '--sidebar-accent',
  },
  {
    name: 'Sidebar accent hover',
    className: 'bg-sidebar-accent-hover',
    label: 'var(--sidebar-accent-hover)',
    token: '--sidebar-accent-hover',
  },
  {
    name: 'Sidebar accent active',
    className: 'bg-sidebar-accent-active',
    label: 'var(--sidebar-accent-active)',
    token: '--sidebar-accent-active',
  },
  {
    name: 'Sidebar accent foreground',
    className: 'bg-sidebar-accent-foreground',
    label: 'var(--sidebar-accent-foreground)',
    token: '--sidebar-accent-foreground',
    invert: true,
  },
  {
    name: 'Sidebar ring',
    className: 'bg-sidebar-ring',
    label: 'var(--sidebar-ring)',
    token: '--sidebar-ring',
    invert: true,
  },
];
